# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 07:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='分类')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='评头')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('content', models.TextField(verbose_name='点评内容')),
                ('like', models.BooleanField(verbose_name='态度')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('source', models.URLField(verbose_name='原文链接')),
                ('publish_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('receipt_time', models.DateTimeField(auto_now=True, verbose_name='收录时间')),
                ('author', models.CharField(max_length=20, verbose_name='作者')),
                ('content', models.TextField(verbose_name='内容')),
                ('likenum', models.IntegerField(verbose_name='喜欢')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Category', verbose_name='分类')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='标签')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='record',
            name='recorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='收录者'),
        ),
        migrations.AddField(
            model_name='evaluate',
            name='recorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Record', verbose_name='记录'),
        ),
        migrations.AddField(
            model_name='evaluate',
            name='tags',
            field=models.ManyToManyField(blank=True, to='Main.Tag', verbose_name='标签集'),
        ),
        migrations.AddField(
            model_name='evaluate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论人'),
        ),
    ]
