# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20161113_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '分类'},
        ),
        migrations.AlterModelOptions(
            name='evaluate',
            options={'verbose_name': '评价'},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name': '记录'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '标签'},
        ),
    ]
