# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_auto_20161113_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='likenum',
            field=models.IntegerField(default=0, verbose_name='喜欢'),
        ),
    ]
