# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 13:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_auto_20161113_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='author',
            field=models.CharField(default='', max_length=20, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='record',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Main.Category', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='record',
            name='content',
            field=models.TextField(default='', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='record',
            name='recorder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='收录者'),
        ),
    ]
