# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_auto_20161118_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='keywords',
            field=models.CharField(default='', max_length=500, verbose_name='关键词'),
        ),
    ]
