# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_auto_20161118_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='keywords',
            field=models.CharField(default='', max_length=1000, verbose_name='关键词'),
        ),
    ]
