# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_auto_20161208_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='keywords',
            field=models.CharField(default='', max_length=5000, verbose_name='关键词'),
        ),
    ]
